# Generated by Django 3.2 on 2021-08-07 03:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('summary', ckeditor.fields.RichTextField()),
                ('url', models.CharField(default='null', max_length=100)),
                ('is_free', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('banner', models.ImageField(upload_to='static/courses/banners/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courses')),
                ('lessons', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='lesson.lesson', verbose_name='Course Lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_authors', to='author.author')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.courses')),
            ],
        ),
    ]
