# Generated by Django 3.2 on 2021-05-03 03:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('summary', ckeditor.fields.RichTextField()),
                ('is_free', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('banner', models.ImageField(upload_to='static/courses/banners/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
