# Generated by Django 3.2 on 2021-05-05 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('courses', '0003_course_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.courses')),
            ],
        ),
    ]
