# Generated by Django 3.2 on 2021-05-10 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
        ('courses', '0005_auto_20210508_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='lessons',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson', verbose_name='Course Lessons'),
        ),
    ]
