# Generated by Django 3.2 on 2021-05-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='lessons',
        ),
    ]
