# Generated by Django 3.2 on 2021-05-11 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('courses', '0008_alter_course_lessons_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_creator',
            name='authors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_authors', to='author.author'),
        ),
    ]
